version: '3'
services:
  chat_node:
    build: ./app
    volumes:
       - ./logs/:/usr/src/app/logs/:w
  chat_nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - chat_node